<?php
//Session start shoul always be the first function
session_start();

//This is going to be a JSON document.
header('Content-type: application/json');

//Only if you want to add some salt to the formula (to make it harder to decipher)
$options = [
    //'cost' => 11, //the number of iteration encriptions
    //'salt' => mcrypt_create_iv(22, PASSWORD_DEFAULT),//to manually provide a salt to use when hashing the password.
];

/**
 * Normally this array is generated by the Database, passwords in this array 
 * are supposed to be generated on the user SignUp and stored into the DB
 * using the exact same hash algorithms that we use in the login because 
 * if you use a different one they will not mach when comparing on login
 **/
$validUsers = [
    [ 'username'=>'alesanchezr', 'password'=> password_hash('1509442',PASSWORD_DEFAULT, $options)],//1509442 is really a hash for 1234 hashed on the front end
    [ 'username'=>'nacho', 'password'=> password_hash('2987074',PASSWORD_DEFAULT, $options)]//1509442 is really a hash for abcd hashed on the front end
];

//print on the document the resulting json
echo processLogin($validUsers);

function processLogin($validUsers){
    $resultingJSON = [ "code" => 401, "msg" => "Invalid username or password"];
    
    $username = $_POST['username'];
    $password = $_POST['password'];
    
    foreach($validUsers as $user)//loop each possible user
    {
        //if that particuar user matches with the inputed username and password
        if($user['username'] == $username && password_verify($password,$user['password']))
        {
            //open the session
            $_SESSION['logged_in'] = true;
            
            //change the $resultingJSON with successfull data 
            $resultingJSON['code'] = 200;
            $resultingJSON['msg'] = 'Welcome!';
        }
    }
    
    //return the JSON
    return json_encode($resultingJSON);
}